version: "3"

services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - '6831:6831'
      - '16686:16686'
      - '14250:14250'

  nonamedb:
    image: nonamedb:1.0.0-SNAPSHOT
    environment:
      - NONAMEDB_LOGLEVEL=DEBUG
      - NONAMEDB_TRACING_ENDPOINT=http://jaeger:14250
    ports:
      - '9000:9000'

networks:
  default:

volumes:
  prometheus_data:
