[package]
name = "nonamedb"
version = "1.0.0-SNAPSHOT"
authors = ["sndnv"]

[dependencies]
lazy_static = "1.0"
RobotS = "0.3.0"
log = "0.3"
env_logger = "0.3"
futures = "0.1.14"
hyper = "0.11.2"
regex = "1.0.0"

[dev-dependencies]
tokio-core = "0.1"

[lib]
name = "nonamedb"
path = "src/lib.rs"
